import type { OrderStatus, OrderStatusTimelineEntry } from '@/domain/models/order'

export const ORDER_STATUS_SEQUENCE: OrderStatus[] = [
  'BOOKING_RECEIVED',
  'PICKUP_SCHEDULED',
  'DRIVER_ASSIGNED',
  'DRIVER_EN_ROUTE',
  'COLLECTED',
  'RECEIVED_AT_STORE',
  'SORTING',
  'WASHING',
  'DRYING',
  'IRONING',
  'QUALITY_CHECK',
  'PACKING',
  'READY_FOR_DISPATCH',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'COMPLETED',
  'CANCELLED',
]

export const ORDER_STATUS_MODEL: Record<OrderStatus, OrderStatusTimelineEntry> = {
  BOOKING_RECEIVED: {
    status: 'BOOKING_RECEIVED',
    label: 'Booking received',
    customerLabel: 'Order confirmed',
    description: 'Your order has been created and awaits scheduling.',
    stage: 'BOOKING',
  },
  PICKUP_SCHEDULED: {
    status: 'PICKUP_SCHEDULED',
    label: 'Pickup scheduled',
    customerLabel: 'Pickup scheduled',
    description: 'A collection slot has been reserved.',
    stage: 'PICKUP',
  },
  DRIVER_ASSIGNED: {
    status: 'DRIVER_ASSIGNED',
    label: 'Driver assigned',
    customerLabel: 'Driver assigned',
    description: 'A LOAD driver has been allocated.',
    stage: 'PICKUP',
  },
  DRIVER_EN_ROUTE: {
    status: 'DRIVER_EN_ROUTE',
    label: 'Driver en route',
    customerLabel: 'Driver on the way',
    description: 'The driver is travelling to the pickup or delivery stop.',
    stage: 'PICKUP',
  },
  COLLECTED: {
    status: 'COLLECTED',
    label: 'Collected',
    customerLabel: 'Collected',
    description: 'Items have been collected from the customer.',
    stage: 'PICKUP',
  },
  RECEIVED_AT_STORE: {
    status: 'RECEIVED_AT_STORE',
    label: 'Received at store',
    customerLabel: 'Received at LOAD store',
    description: 'Items have arrived at the processing site.',
    stage: 'PRODUCTION',
  },
  SORTING: {
    status: 'SORTING',
    label: 'Sorting',
    customerLabel: 'Sorting',
    description: 'Items are being sorted for treatment.',
    stage: 'PRODUCTION',
  },
  WASHING: {
    status: 'WASHING',
    label: 'Washing',
    customerLabel: 'Washing',
    description: 'Garments are in the wash cycle.',
    stage: 'PRODUCTION',
  },
  DRYING: {
    status: 'DRYING',
    label: 'Drying',
    customerLabel: 'Drying',
    description: 'Items are drying with the selected care profile.',
    stage: 'PRODUCTION',
  },
  IRONING: {
    status: 'IRONING',
    label: 'Ironing',
    customerLabel: 'Ironing',
    description: 'Pressed finishing is in progress.',
    stage: 'PRODUCTION',
  },
  QUALITY_CHECK: {
    status: 'QUALITY_CHECK',
    label: 'Quality check',
    customerLabel: 'Quality check',
    description: 'Final garment inspection is underway.',
    stage: 'PRODUCTION',
  },
  PACKING: {
    status: 'PACKING',
    label: 'Packing',
    customerLabel: 'Packing',
    description: 'Clean items are being packed for dispatch.',
    stage: 'PRODUCTION',
  },
  READY_FOR_DISPATCH: {
    status: 'READY_FOR_DISPATCH',
    label: 'Ready for dispatch',
    customerLabel: 'Ready for delivery',
    description: 'The order is prepared for route planning.',
    stage: 'DELIVERY',
  },
  OUT_FOR_DELIVERY: {
    status: 'OUT_FOR_DELIVERY',
    label: 'Out for delivery',
    customerLabel: 'Out for delivery',
    description: 'A driver is taking the order back to the customer.',
    stage: 'DELIVERY',
  },
  DELIVERED: {
    status: 'DELIVERED',
    label: 'Delivered',
    customerLabel: 'Delivered',
    description: 'The customer has received the order.',
    stage: 'DELIVERY',
  },
  COMPLETED: {
    status: 'COMPLETED',
    label: 'Completed',
    customerLabel: 'Completed',
    description: 'The order lifecycle is complete.',
    stage: 'CLOSED',
  },
  CANCELLED: {
    status: 'CANCELLED',
    label: 'Cancelled',
    customerLabel: 'Cancelled',
    description: 'The order has been cancelled.',
    stage: 'CLOSED',
  },
}

export const getFriendlyOrderStatus = (status: OrderStatus) =>
  ORDER_STATUS_MODEL[status].customerLabel
