import type { OrderStatus, OrderStatusTimelineEntry } from '@/domain/models/order'

export const ORDER_STATUS_SEQUENCE: OrderStatus[] = [
  'BOOKING_RECEIVED',
  'PICKUP_SCHEDULED',
  'DRIVER_ASSIGNED',
  'DRIVER_EN_ROUTE',
  'DRIVER_ARRIVED',
  'COLLECTION_VERIFIED',
  'COLLECTED',
  'WEIGHT_CONFIRMED',
  'AWAITING_PAYMENT',
  'PAYMENT_CONFIRMED',
  'RECEIVED_AT_STORE',
  'SORTING',
  'WASHING',
  'DRYING',
  'IRONING',
  'QUALITY_CHECK',
  'PACKING',
  'READY_FOR_DISPATCH',
  'DELIVERY_SCHEDULED',
  'OUT_FOR_DELIVERY',
  'DELIVERED',
  'COMPLETED',
  'RESCHEDULED',
  'CANCELLED',
]

export const ORDER_STATUS_MODEL: Record<OrderStatus, OrderStatusTimelineEntry> = {
  BOOKING_RECEIVED: {
    status: 'BOOKING_RECEIVED',
    label: 'Booking received',
    customerLabel: 'Order confirmed',
    description: 'Your order has been created and awaits scheduling.',
    stage: 'BOOKING',
  },
  PICKUP_SCHEDULED: {
    status: 'PICKUP_SCHEDULED',
    label: 'Pickup scheduled',
    customerLabel: 'Pickup scheduled',
    description: 'A collection slot has been reserved.',
    stage: 'PICKUP',
  },
  DRIVER_ASSIGNED: {
    status: 'DRIVER_ASSIGNED',
    label: 'Driver assigned',
    customerLabel: 'Driver assigned',
    description: 'A LOAD driver has been allocated.',
    stage: 'PICKUP',
  },
  DRIVER_EN_ROUTE: {
    status: 'DRIVER_EN_ROUTE',
    label: 'Driver en route',
    customerLabel: 'Driver on the way',
    description: 'The driver is travelling to the pickup address.',
    stage: 'PICKUP',
  },
  DRIVER_ARRIVED: {
    status: 'DRIVER_ARRIVED',
    label: 'Driver arrived',
    customerLabel: 'Driver arrived',
    description: 'The driver has arrived at your address.',
    stage: 'PICKUP',
  },
  COLLECTION_VERIFIED: {
    status: 'COLLECTION_VERIFIED',
    label: 'Collection verified',
    customerLabel: 'Collection verified',
    description: 'Identity has been verified for collection.',
    stage: 'PICKUP',
  },
  COLLECTED: {
    status: 'COLLECTED',
    label: 'Collected',
    customerLabel: 'Collected',
    description: 'Items have been collected from you.',
    stage: 'PICKUP',
  },
  WEIGHT_CONFIRMED: {
    status: 'WEIGHT_CONFIRMED',
    label: 'Weight confirmed',
    customerLabel: 'Weight confirmed',
    description: 'The laundry has been weighed and the price confirmed.',
    stage: 'PICKUP',
  },
  AWAITING_PAYMENT: {
    status: 'AWAITING_PAYMENT',
    label: 'Awaiting payment',
    customerLabel: 'Payment required',
    description: 'Please complete payment to proceed.',
    stage: 'PICKUP',
  },
  PAYMENT_CONFIRMED: {
    status: 'PAYMENT_CONFIRMED',
    label: 'Payment confirmed',
    customerLabel: 'Payment confirmed',
    description: 'Your payment has been received.',
    stage: 'PICKUP',
  },
  RECEIVED_AT_STORE: {
    status: 'RECEIVED_AT_STORE',
    label: 'Received at store',
    customerLabel: 'Received at LOAD store',
    description: 'Items have arrived at the processing site.',
    stage: 'PRODUCTION',
  },
  SORTING: {
    status: 'SORTING',
    label: 'Sorting',
    customerLabel: 'Sorting',
    description: 'Items are being sorted for treatment.',
    stage: 'PRODUCTION',
  },
  WASHING: {
    status: 'WASHING',
    label: 'Washing',
    customerLabel: 'Washing',
    description: 'Garments are in the wash cycle.',
    stage: 'PRODUCTION',
  },
  DRYING: {
    status: 'DRYING',
    label: 'Drying',
    customerLabel: 'Drying',
    description: 'Items are drying with your selected care profile.',
    stage: 'PRODUCTION',
  },
  IRONING: {
    status: 'IRONING',
    label: 'Ironing',
    customerLabel: 'Ironing',
    description: 'Pressed finishing is in progress.',
    stage: 'PRODUCTION',
  },
  QUALITY_CHECK: {
    status: 'QUALITY_CHECK',
    label: 'Quality check',
    customerLabel: 'Quality check',
    description: 'Final garment inspection is underway.',
    stage: 'PRODUCTION',
  },
  PACKING: {
    status: 'PACKING',
    label: 'Packing',
    customerLabel: 'Packing',
    description: 'Clean items are being packed for dispatch.',
    stage: 'PRODUCTION',
  },
  READY_FOR_DISPATCH: {
    status: 'READY_FOR_DISPATCH',
    label: 'Ready for dispatch',
    customerLabel: 'Ready for delivery',
    description: 'The order is prepared for route planning.',
    stage: 'DELIVERY',
  },
  DELIVERY_SCHEDULED: {
    status: 'DELIVERY_SCHEDULED',
    label: 'Delivery scheduled',
    customerLabel: 'Delivery scheduled',
    description: 'A delivery time has been confirmed.',
    stage: 'DELIVERY',
  },
  OUT_FOR_DELIVERY: {
    status: 'OUT_FOR_DELIVERY',
    label: 'Out for delivery',
    customerLabel: 'Out for delivery',
    description: 'A driver is bringing your order back to you.',
    stage: 'DELIVERY',
  },
  DELIVERED: {
    status: 'DELIVERED',
    label: 'Delivered',
    customerLabel: 'Delivered',
    description: 'Your order has been delivered.',
    stage: 'DELIVERY',
  },
  COMPLETED: {
    status: 'COMPLETED',
    label: 'Completed',
    customerLabel: 'Completed',
    description: 'The order lifecycle is complete.',
    stage: 'CLOSED',
  },
  RESCHEDULED: {
    status: 'RESCHEDULED',
    label: 'Rescheduled',
    customerLabel: 'Rescheduled',
    description: 'This stop has been rescheduled.',
    stage: 'CLOSED',
  },
  CANCELLED: {
    status: 'CANCELLED',
    label: 'Cancelled',
    customerLabel: 'Cancelled',
    description: 'The order has been cancelled.',
    stage: 'CLOSED',
  },
}

export const getFriendlyOrderStatus = (status: OrderStatus) =>
  ORDER_STATUS_MODEL[status].customerLabel
